refacto authors
NodeSecure/scanner pull request #62
Opened 2022-08-14 19:12 UTC by Kawacrepe

2022-08-14 19:19 UTC, Kawacrepe commented
We may want to create a different issue about the TODO I put in the code.
This is mostly related to RC, we may want to give this opportunity to someone who wants to start contributing.

It consist in adding `flags` & `domainInformations` in RC and use em in scanner

2022-08-14 19:20 UTC, Kawacrepe commented
We may want to create a different issue about the TODO I put in the code.
This is mostly related to RC, we may want to give this opportunity to someone who wants to start contributing.

It consist in adding `flags` & `domainInformations` in RC and use em in scanner

2022-08-15 14:50 UTC, fraxken requested changes

2022-08-15 14:50 UTC, fraxken commented on src/utils/warnings.js
> +const KFlags = [{
`k` should always be in lowercase. `kFlaggedAuthors` ?

2022-08-15 14:51 UTC, fraxken commented
This line should be updated: https://github.com/NodeSecure/scanner/blob/master/src/depWalker.js#L326

2022-08-31 19:35 UTC, Kawacrepe commented
@fraxken What do you think about this kind of payload ?

```js
{
  warnings: {
    globals: globalsWarning,
    flaggedAuthors: xx.filter((el) => el.flagged === true))
  },
  authors,
}
```

It may be future-proof (I'm thinking about nodesecure/rc atm)

2022-09-02 17:20 UTC, fraxken commented
@Kawacrepe do we really need to touch the global `warnings` key ? Because for me if the flag information is in the list of authors we do not need to repeat the information.

Then for me it's the responsability of tools to filter flagged authors (like in Scanner / UI / CI ..).

2022-09-03 08:44 UTC, Kawacrepe commented
Oh okay, looks like I didn't understood one of your messages in the discord channel

2022-10-03 19:05 UTC, Kawacrepe commented
Thank's to this suit of tests, Now, we know we need to release an author version that handle scenario when there is no authors, name & email in the given dependency

2023-02-12 00:15 UTC, fraxken approved these changes

2023-02-12 00:15 UTC, merged

2023-02-12 00:16 UTC, fraxken commented
@all-contributors please add @Kawacrepe for code